

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/dbname
    depends_on:
      - postgres
    networks:
      - tauri-network

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tauri-network

volumes:
  postgres-data:

networks:
  tauri-network:
    driver: bridge
